# CMake generated Testfile for 
# Source directory: C:/reji-studio/tests
# Build directory: C:/reji-studio/build_debug/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ffi_boundary]=] "C:/reji-studio/build_debug/tests/Debug/test_ffi_boundary.exe")
  set_tests_properties([=[ffi_boundary]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;20;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ffi_boundary]=] "C:/reji-studio/build_debug/tests/Release/test_ffi_boundary.exe")
  set_tests_properties([=[ffi_boundary]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;20;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ffi_boundary]=] "C:/reji-studio/build_debug/tests/MinSizeRel/test_ffi_boundary.exe")
  set_tests_properties([=[ffi_boundary]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;20;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ffi_boundary]=] "C:/reji-studio/build_debug/tests/RelWithDebInfo/test_ffi_boundary.exe")
  set_tests_properties([=[ffi_boundary]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;20;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
else()
  add_test([=[ffi_boundary]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[FrameProfilerTest]=] "C:/reji-studio/build_debug/tests/Debug/test_frame_profiler.exe")
  set_tests_properties([=[FrameProfilerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;32;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[FrameProfilerTest]=] "C:/reji-studio/build_debug/tests/Release/test_frame_profiler.exe")
  set_tests_properties([=[FrameProfilerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;32;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[FrameProfilerTest]=] "C:/reji-studio/build_debug/tests/MinSizeRel/test_frame_profiler.exe")
  set_tests_properties([=[FrameProfilerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;32;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[FrameProfilerTest]=] "C:/reji-studio/build_debug/tests/RelWithDebInfo/test_frame_profiler.exe")
  set_tests_properties([=[FrameProfilerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;32;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
else()
  add_test([=[FrameProfilerTest]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ShaderCacheTest]=] "C:/reji-studio/build_debug/tests/Debug/test_shader_cache.exe")
  set_tests_properties([=[ShaderCacheTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;44;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ShaderCacheTest]=] "C:/reji-studio/build_debug/tests/Release/test_shader_cache.exe")
  set_tests_properties([=[ShaderCacheTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;44;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ShaderCacheTest]=] "C:/reji-studio/build_debug/tests/MinSizeRel/test_shader_cache.exe")
  set_tests_properties([=[ShaderCacheTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;44;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ShaderCacheTest]=] "C:/reji-studio/build_debug/tests/RelWithDebInfo/test_shader_cache.exe")
  set_tests_properties([=[ShaderCacheTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/reji-studio/tests/CMakeLists.txt;44;add_test;C:/reji-studio/tests/CMakeLists.txt;0;")
else()
  add_test([=[ShaderCacheTest]=] NOT_AVAILABLE)
endif()
subdirs("../_deps/googletest-build")
