#pragma once
#include <stdint.h>
#include <stddef.h>

/* ── Auto-generated types and declarations (cbindgen C++ mode) ──────────── */
/* ffi_auto.h, C++ standard başlıkları içerdiğinden extern "C" dışında     */
/* include edilmeli. cbindgen C++ modunda fonksiyonlar kendi extern "C"     */
/* annotation'larıyla üretilir.                                             */
/* Provides: MetricSample, RjCommand, RjAction, RjActionType, RjActionEvent,*/
/*           rj_start_monitor, rj_metrics_push, rj_command_drain,          */
/*           rj_pipeline_status, rj_connection_lost, rj_action_dequeue,    */
/*           rj_action_event_dequeue, rj_action_approve, rj_action_reject, */
/*           rj_set_action_auto_approve, rj_set_healing_mode,             */
/*           rj_get_healing_mode, rj_reload_rules                          */
#include "ffi_auto.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ── RjMetricSample: canonical C++ alias for MetricSample ──────────────── */
/* Layout identical (64 bytes); field 'source_id' (0=video, 1=audio) is at    */
/* offset +55, magic_tail at +56 (bkz. ffi_auto.h / metrics.rs).              */
typedef MetricSample RjMetricSample;

/* ── Bridge-specific constants ──────────────────────────────────────────── */
#define RJ_FFI_VERSION  0x00010000u  /* 1.0.0 */
#define RJ_METRIC_MAGIC 0xEEFF1234u

/* ── Healing mode (bridge-specific, not generated by cbindgen) ──────────── */
// RJ_MODE_AUTO    = 0
// RJ_MODE_COPILOT = 1
// RJ_MODE_ASSIST  = 2
// RJ_MODE_MANUAL  = 3
typedef enum {
    RJ_MODE_AUTO_PILOT = 0,
    RJ_MODE_CO_PILOT   = 1,
    RJ_MODE_ASSIST     = 2,
    RJ_MODE_MANUAL     = 3,
} RjHealingMode;

/* ── Legacy command type (bridge-specific, not generated by cbindgen) ───── */
typedef enum {
    RJ_CMD_SCENE_SWITCH = 0,
    RJ_CMD_BITRATE_SET  = 1,
    RJ_CMD_PREVIEW_FPS  = 2,
} RjCommandType;

/* ── Compat macros: RJ_ACTION_* → ffi_auto.h RjActionType enum values ───── */
#define RJ_ACTION_BITRATE_REDUCE     BitrateReduce
#define RJ_ACTION_BITRATE_RECOVER    BitrateRecover
#define RJ_ACTION_SCALE_RESOLUTION   ScaleResolution
#define RJ_ACTION_RESTORE_RESOLUTION RestoreResolution
#define RJ_ACTION_CAP_FPS            CapFps
#define RJ_ACTION_RESTORE_FPS        RestoreFps
#define RJ_ACTION_LOG_ONLY           LogOnly

/* ── V8/I33: RjActionEvent.kind değerleri (ffi.rs RJ_ACTION_EVENT_* eşleşir) ─── */
#define RJ_ACTION_EVENT_NEW          0u  /* yeni event (bilgi veya onay isteği)   */
#define RJ_ACTION_EVENT_INVALIDATED  1u  /* pending TTL doldu / mod değişti        */

/* ── V8/I33: rj_set_action_auto_approve kategorileri (ffi.rs RJ_ACTION_CAT_*) ── */
#define RJ_ACTION_CAT_BITRATE        0u
#define RJ_ACTION_CAT_RESOLUTION     1u
#define RJ_ACTION_CAT_FPS            2u

/* ── Bridge-specific declarations (not in ffi_auto.h) ───────────────────── */
__declspec(noinline) extern int rj_metrics_poll(RjMetricSample* out);
uint32_t rj_ffi_version(void);

/* ── WS command queue: Rust → C++ (data-driven, no handle/registry) ─────── */
/* cmd=1 stream_start  cmd=2 stream_stop  cmd=3 scene_cut  cmd=4 scene_fade  */
/* cmd=5 set_scene (param = 0-based sahne indeksi)                            */
/* rj_ws_command_v2 / rj_ws_command_dequeue declared in ffi_auto.h           */
/* rj_push_scene_names / rj_user_event_scene_switch declared in ffi_auto.h    */

#ifdef __cplusplus
}
#endif
