#pragma once
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Auto-generated types and declarations (cbindgen) ───────────────────── */
/* Provides: MetricSample, RjCommand, RjAction, RjActionType,            */
/*           rj_start_monitor, rj_metrics_push, rj_command_drain,        */
/*           rj_pipeline_status, rj_connection_lost, rj_action_dequeue,  */
/*           rj_action_approve, rj_set_healing_mode, rj_get_healing_mode,*/
/*           rj_reload_rules                                              */
#include "ffi_auto.h"

/* ── RjMetricSample: canonical C++ alias for MetricSample ──────────────── */
/* Layout identical (56 bytes); field 'reserved' is '_reserved' in MetricSample */
typedef MetricSample RjMetricSample;

/* ── Bridge-specific constants ──────────────────────────────────────────── */
#define RJ_FFI_VERSION  0x00010000u  /* 1.0.0 */
#define RJ_METRIC_MAGIC 0xEEFF1234u

/* ── Healing mode (bridge-specific, not generated by cbindgen) ──────────── */
typedef enum {
    RJ_MODE_AUTO_PILOT = 0,
    RJ_MODE_CO_PILOT   = 1,
    RJ_MODE_ASSIST     = 2,
    RJ_MODE_MANUAL     = 3,
} RjHealingMode;

/* ── Legacy command type (bridge-specific, not generated by cbindgen) ───── */
typedef enum {
    RJ_CMD_SCENE_SWITCH = 0,
    RJ_CMD_BITRATE_SET  = 1,
    RJ_CMD_PREVIEW_FPS  = 2,
} RjCommandType;

/* ── Compat macros: RJ_ACTION_* → ffi_auto.h RjActionType enum values ───── */
#define RJ_ACTION_BITRATE_REDUCE     BitrateReduce
#define RJ_ACTION_BITRATE_RECOVER    BitrateRecover
#define RJ_ACTION_SCALE_RESOLUTION   ScaleResolution
#define RJ_ACTION_RESTORE_RESOLUTION RestoreResolution
#define RJ_ACTION_CAP_FPS            CapFps
#define RJ_ACTION_RESTORE_FPS        RestoreFps
#define RJ_ACTION_LOG_ONLY           LogOnly

/* ── Bridge-specific declarations (not in ffi_auto.h) ───────────────────── */
__declspec(noinline) extern int rj_metrics_poll(RjMetricSample* out);
uint32_t rj_ffi_version(void);

#ifdef __cplusplus
}
#endif
